[tool.black]
line-length = 119
target-version = ['py311']
extend-exclude = "(migrations)"
# Exclude these even if they're passed explicitly as a CLI argument.
# This is necessary for pre-commit to not reformat them.
force-exclude = "(migrations)"

[tool.django-stubs]
django_settings_module = "djangosocial.settings.dev"

[tool.mypy]
exclude = [
  "migrations",
  "tests",
  "manage.py",
  "(a|w)sgi.py",
]
plugins = [
  "mypy_django_plugin.main",
]

[[tool.mypy.overrides]]
module = [
  "djangorestframework.*",
  "wagtail.*",
]
ignore_missing_imports = true

[tool.ruff]
extend-exclude = ["migrations"]
extend-select = [
    "A",   # flake8-builtins
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "C90", # mccabe
    "COM", # flake8-commas
    "D",   # pydocstyle
    "DJ",  # flake8-django
    "I",   # isort
    "LOG", # flake8-logging
    "N",   # pep8-naming
    "PTH", # flake8-use-pathlib
    "RUF", # Ruff-specific rules
    "SIM", # flake8-simplify
    "UP",  # pyupgrade
    "W"    # pycodestyle Warning
]
fix = false
line-length = 119
target-version = "py311"
